services:
  db:
    image: postgres:16-alpine
    container_name: ci-cd-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ci_cd_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ci-cd-redis
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci-cd-api
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ci_cd_api?schema=public
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
