name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npm run ts

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      # Install k6
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz
          sudo cp k6-v0.49.0-linux-amd64/k6 /usr/local/bin

      # Lancer le serveur en arrière plan
      - name: Start server
        run: npm start &
        env:
          PORT: 3000
          NODE_ENV: production

      # Attendre que le serveur soit prêt
      - name: Wait for server
        run: sleep 5

      # Lancer le test de charge
      - name: Run k6 load test
        run: k6 run load-test.js

      # Connecter GitHub Actions à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: .Dockerfile
          push: true
          tags: |
            aissaninadia/ci-cd-api:latest
            aissaninadia/ci-cd-api:${{ github.sha }}
            aissaninadia/ci-cd-api:v1.1.0

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}